/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unicamp.ft.lojadamusica.janelas.produtos;

import br.unicamp.ft.lojadamusica.armazenamento.Arquivo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author José Henrique
 */
public class EscolhaDeProduto extends javax.swing.JFrame {
    private Arquivo vArquivo;
    private JTextField TF_CodPro;
    private JTextField TF_ValUni;
    private int qtdest;
    /**
     * Creates new form EscolherProduto
     */
    public EscolhaDeProduto() throws IOException, ClassNotFoundException {
        initComponents();        
        this.setLocationRelativeTo(null);
        vArquivo = new Arquivo("produtos.txt");
        vArquivo.carregarArquivo();
        ProcDadosPro vProcDados = new ProcDadosPro();
        vProcDados.getLista(T_Produtos, vArquivo, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T_Produtos = new javax.swing.JTable();
        EscProd_Button_OK = new javax.swing.JButton();
        EscProd_Button_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loja da Música - Escolher produto");
        setAlwaysOnTop(true);
        setResizable(false);

        T_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição do produto", "Preço Venda", "Qtd. Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(T_Produtos);

        EscProd_Button_OK.setText("OK");
        EscProd_Button_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscProd_Button_OKMouseClicked(evt);
            }
        });

        EscProd_Button_Cancelar.setText("Cancelar");
        EscProd_Button_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscProd_Button_CancelarMouseClicked(evt);
            }
        });
        EscProd_Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscProd_Button_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EscProd_Button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EscProd_Button_Cancelar)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscProd_Button_OK)
                    .addComponent(EscProd_Button_Cancelar))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EscProd_Button_OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscProd_Button_OKMouseClicked
        int index = T_Produtos.getSelectedRow();
        if(index >= 0){
            String codigo = T_Produtos.getValueAt(index, 0).toString();
            String valor = T_Produtos.getValueAt(index, 2).toString();
            TF_CodPro.setText(codigo);
            TF_ValUni.setText(valor);            
            dispose();
        }else
            JOptionPane.showMessageDialog(null, "Selecione um Produto!");
    }//GEN-LAST:event_EscProd_Button_OKMouseClicked

    private void EscProd_Button_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscProd_Button_CancelarMouseClicked
        
    }//GEN-LAST:event_EscProd_Button_CancelarMouseClicked

    private void EscProd_Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscProd_Button_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_EscProd_Button_CancelarActionPerformed

    public void carregaInfo(JTextField TF_CodPro, JTextField TF_ValUni){
        this.TF_CodPro = TF_CodPro;
        this.TF_ValUni = TF_ValUni;        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EscolhaDeProduto().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(EscolhaDeProduto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EscolhaDeProduto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EscProd_Button_Cancelar;
    private javax.swing.JButton EscProd_Button_OK;
    private javax.swing.JTable T_Produtos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
