/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unicamp.ft.lojadamusica.janelas.clientes;

import br.unicamp.ft.lojadamusica.armazenamento.Arquivo;
import br.unicamp.ft.lojadamusica.janelas.vendas.cabecalho.ProcDadosVen;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author José Henrique
 */
public class PesqCliente extends javax.swing.JFrame {
    private Arquivo vArquivo;

    /**
     * Creates new form Clientes
     */
    public PesqCliente() throws IOException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        vArquivo = new Arquivo("cliente.txt");
        vArquivo.carregarArquivo();
        ProcDadosCli vProcDados = new ProcDadosCli();
        vProcDados.getLista(T_Clientes, vArquivo, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SP_Clientes = new javax.swing.JScrollPane();
        T_Clientes = new javax.swing.JTable();
        MB_MenuCliente = new javax.swing.JMenuBar();
        M_Incluir = new javax.swing.JMenu();
        M_Alterar = new javax.swing.JMenu();
        M_Excluir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        T_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "RG", "CPF/CNPJ", "Endereço", "Número", "Bairro", "CEP", "Cidade", "UF"
            }
        ));
        T_Clientes.setColumnSelectionAllowed(true);
        T_Clientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SP_Clientes.setViewportView(T_Clientes);
        T_Clientes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        M_Incluir.setText("Incluir");
        M_Incluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_IncluirMouseClicked(evt);
            }
        });
        M_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_IncluirActionPerformed(evt);
            }
        });
        MB_MenuCliente.add(M_Incluir);

        M_Alterar.setText("Alterar");
        M_Alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_AlterarMouseClicked(evt);
            }
        });
        M_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_AlterarActionPerformed(evt);
            }
        });
        MB_MenuCliente.add(M_Alterar);

        M_Excluir.setText("Excluir");
        M_Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_ExcluirMouseClicked(evt);
            }
        });
        MB_MenuCliente.add(M_Excluir);

        setJMenuBar(MB_MenuCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SP_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SP_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void M_IncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_IncluirMouseClicked
        InclusaoDeCliente varincclientes = new InclusaoDeCliente();
        varincclientes.carregaInfo(vArquivo, "I", T_Clientes, 0);
        varincclientes.show();     
    }//GEN-LAST:event_M_IncluirMouseClicked

    private void M_AlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_AlterarMouseClicked
        InclusaoDeCliente varaltclientes = new InclusaoDeCliente();
        int index = T_Clientes.getSelectedRow();
        if(index >= 0){
            varaltclientes.carregaInfo(vArquivo, "A", T_Clientes, index);
            varaltclientes.show();
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um Cliente!");
            return;
        }
    }//GEN-LAST:event_M_AlterarMouseClicked

    private void M_ExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_ExcluirMouseClicked
        try {
            int index = T_Clientes.getSelectedRow();
            ProcDadosCli vFuncGer = new ProcDadosCli();
            if(index >= 0){
                if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o cliente?") == 0){ 
                    ProcDadosVen vProcDados = new  ProcDadosVen();
                    int codigo = Integer.valueOf(T_Clientes.getValueAt(index, 0).toString());
                    if(!vProcDados.verificaExc(1, codigo)){
                        JOptionPane.showMessageDialog(null, "Existem Vendas com esse Cliente!");
                        return;
                    }
                    vFuncGer.excluirCliente(index, T_Clientes, vArquivo);
                    JOptionPane.showMessageDialog(null, "Cliente Excluído com Sucesso!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um Cliente!");
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(PesqCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PesqCliente.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_M_ExcluirMouseClicked

    private void M_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_IncluirActionPerformed
        
    }//GEN-LAST:event_M_IncluirActionPerformed

    private void M_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_AlterarActionPerformed

    }//GEN-LAST:event_M_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PesqCliente().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PesqCliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PesqCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MB_MenuCliente;
    private javax.swing.JMenu M_Alterar;
    private javax.swing.JMenu M_Excluir;
    private javax.swing.JMenu M_Incluir;
    private javax.swing.JScrollPane SP_Clientes;
    private javax.swing.JTable T_Clientes;
    // End of variables declaration//GEN-END:variables
}
