/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ft.lojadamusica.janelas.fornecedores;

import br.unicamp.ft.lojadamusica.armazenamento.Arquivo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Guillhermm
 */
public class EscolhaDeFornecedor extends javax.swing.JFrame {
    private Arquivo vArquivo;
    private JTextField TF_CodForn;
    /**
     * Creates new form EscolherFornecedor
     */
    public EscolhaDeFornecedor() throws IOException, ClassNotFoundException {
        initComponents();        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        vArquivo = new Arquivo("fornecedor.txt");
        vArquivo.carregarArquivo();
        ProcDadosForn vProcDados = new ProcDadosForn();
        vProcDados.getLista(T_Fornecedor, vArquivo, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T_Fornecedor = new javax.swing.JTable();
        EscForn_Button_OK = new javax.swing.JButton();
        EscForn_Button_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loja da Musica - Escolher fornecedor");

        T_Fornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Fornecedor", "Nome do Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(T_Fornecedor);

        EscForn_Button_OK.setText("OK");
        EscForn_Button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscForn_Button_OKActionPerformed(evt);
            }
        });

        EscForn_Button_Cancelar.setText("Cancelar");
        EscForn_Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscForn_Button_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EscForn_Button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EscForn_Button_Cancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EscForn_Button_OK)
                    .addComponent(EscForn_Button_Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EscForn_Button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscForn_Button_OKActionPerformed
        int index = T_Fornecedor.getSelectedRow();
        if(index >= 0){
            String codigo = T_Fornecedor.getValueAt(index, 0).toString();            
            TF_CodForn.setText(codigo);            
            dispose();
        }else
            JOptionPane.showMessageDialog(null, "Selecione um Fornecedor!");
    }//GEN-LAST:event_EscForn_Button_OKActionPerformed

    private void EscForn_Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscForn_Button_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_EscForn_Button_CancelarActionPerformed

    public void carregaInfo(JTextField TF_CodForn){
        this.TF_CodForn = TF_CodForn;        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EscolhaDeFornecedor().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(EscolhaDeFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EscolhaDeFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EscForn_Button_Cancelar;
    private javax.swing.JButton EscForn_Button_OK;
    private javax.swing.JTable T_Fornecedor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
