/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ft.lojadamusica.janelas.fornecedores;

import br.unicamp.ft.lojadamusica.armazenamento.Arquivo;
import br.unicamp.ft.lojadamusica.janelas.fornecedores.Fornecedor;
import br.unicamp.ft.lojadamusica.janelas.fornecedores.InclusaoDeFornecedor;
import br.unicamp.ft.lojadamusica.janelas.fornecedores.ProcDadosForn;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Zeh Fiorillo
 */
public class InclusaoDeFornecedor extends javax.swing.JFrame {

    private Arquivo vArquivo;
    private String tipo;
    private JTable grid;
    private int index;
    /**
     * Creates new form IncFornecedores
     */
    public InclusaoDeFornecedor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        TF_Endereco = new javax.swing.JTextField();
        TF_UF = new javax.swing.JTextField();
        TF_Numero = new javax.swing.JTextField();
        B_Gravar = new javax.swing.JButton();
        L_Endereco = new javax.swing.JLabel();
        B_Cancelar = new javax.swing.JButton();
        TF_Codigo = new javax.swing.JTextField();
        L_Numero = new javax.swing.JLabel();
        L_Nome = new javax.swing.JLabel();
        L_Bairro = new javax.swing.JLabel();
        TF_Nome = new javax.swing.JTextField();
        TF_Bairro = new javax.swing.JTextField();
        TF_RG = new javax.swing.JTextField();
        L_CEP = new javax.swing.JLabel();
        L_RG = new javax.swing.JLabel();
        TF_CEP = new javax.swing.JTextField();
        RB_CNPJ = new javax.swing.JRadioButton();
        TF_Cidade = new javax.swing.JTextField();
        RB_CPF = new javax.swing.JRadioButton();
        L_Cidade = new javax.swing.JLabel();
        TF_Documento = new javax.swing.JTextField();
        L_UF = new javax.swing.JLabel();
        L_Codigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        B_Gravar.setText("Gravar");
        B_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GravarActionPerformed(evt);
            }
        });

        L_Endereco.setText("Endereço:");

        B_Cancelar.setText("Cancelar");
        B_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CancelarActionPerformed(evt);
            }
        });

        TF_Codigo.setEditable(false);
        TF_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CodigoActionPerformed(evt);
            }
        });

        L_Numero.setText("Número:");

        L_Nome.setText("Nome:");

        L_Bairro.setText("Bairro:");

        L_CEP.setText("CEP:");

        L_RG.setText("R.G.:");

        buttonGroup1.add(RB_CNPJ);
        RB_CNPJ.setText("CNPJ:");
        RB_CNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_CNPJActionPerformed(evt);
            }
        });

        buttonGroup1.add(RB_CPF);
        RB_CPF.setText("CPF:");

        L_Cidade.setText("Cidade:");

        L_UF.setText("U.F.:");

        L_Codigo.setText("Código:");
        L_Codigo.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Nome)
                    .addComponent(L_RG)
                    .addComponent(L_Endereco)
                    .addComponent(L_Numero)
                    .addComponent(L_Cidade)
                    .addComponent(L_Codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TF_Nome)
                    .addComponent(TF_Endereco)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TF_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RB_CNPJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RB_CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TF_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L_UF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TF_UF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TF_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L_Bairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TF_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L_CEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(B_Gravar)
                                .addGap(18, 18, 18)
                                .addComponent(B_Cancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_RG)
                    .addComponent(RB_CNPJ)
                    .addComponent(RB_CPF)
                    .addComponent(TF_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Endereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Numero)
                    .addComponent(L_Bairro)
                    .addComponent(TF_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_CEP)
                    .addComponent(TF_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Cidade)
                    .addComponent(L_UF)
                    .addComponent(TF_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Gravar)
                    .addComponent(B_Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB_CNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_CNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_CNPJActionPerformed

    private void B_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GravarActionPerformed
        int tipdoc;
        if(TF_Nome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Nome é Obrigatório!");
            return;
        }            
        if(TF_RG.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo R.G. é Obrigatório!");
            return;
        }          
        if(TF_Documento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo CPF/CNPJ é Obrigatório!");
            return;
        }
        if(RB_CNPJ.isSelected())        
            tipdoc = 0;
        else
            tipdoc = 1;
        
        Fornecedor vFornecedor = new Fornecedor(Integer.valueOf(TF_Codigo.getText()), 
                                                                TF_Nome.getText(), 
                                                                TF_RG.getText(),
                                                                tipdoc,                                                       
                                                                TF_Documento.getText(),
                                                                TF_Endereco.getText(),
                                                                TF_Numero.getText(),
                                                                TF_Bairro.getText(),
                                                                TF_CEP.getText(),
                                                                TF_Cidade.getText(),
                                                                TF_UF.getText());
        
        String texto;
        if(tipo=="I"){
            vArquivo.salvaLista(tipo, 0, vFornecedor);
            texto = "Cadastrado";
        }
        else{
            vArquivo.salvaLista(tipo, index, vFornecedor);
            texto = "Alterado";
        }
        try {
            vArquivo.gravarLista();
        } catch (IOException ex) {
            Logger.getLogger(InclusaoDeFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ProcDadosForn vProcDadosForn = new ProcDadosForn();
        vProcDadosForn.getLista(grid, vArquivo, 0);
            
        JOptionPane.showMessageDialog(null, "Fornecedor " + texto + " com Sucesso!");
        dispose();
    }//GEN-LAST:event_B_GravarActionPerformed

    private void TF_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CodigoActionPerformed

    private void B_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_B_CancelarActionPerformed

    public void carregaInfo(Arquivo vArquivo, String tipo, JTable grid, int index){
        this.vArquivo = vArquivo;
        this.tipo = tipo;
        this.grid = grid;
        this.index = index;
        if(tipo == "I"){
            int codigo;
            if(this.vArquivo.lista.size()>0)
                codigo = Integer.valueOf(grid.getValueAt(this.vArquivo.lista.size()-1, 0).toString())+1;
            else
                codigo = 1;
            TF_Codigo.setText(String.valueOf(codigo));
        }            
        else
            Alterar();
    }
    
    public void Alterar(){
        int index = this.grid.getSelectedRow();                
        TF_Codigo.setText(this.grid.getValueAt(index, 0).toString());
        TF_Nome.setText(this.grid.getValueAt(index, 1).toString());
        TF_RG.setText(this.grid.getValueAt(index, 2).toString());
        ProcDadosForn vProcDados = new ProcDadosForn();
        if(vProcDados.retornaCombo(this.vArquivo, this.index)==0)
            RB_CNPJ.setSelected(true);
        else
            RB_CPF.setSelected(true);
        TF_Documento.setText(this.grid.getValueAt(index, 3).toString());
        TF_Endereco.setText(this.grid.getValueAt(index, 4).toString());
        TF_Numero.setText(this.grid.getValueAt(index, 5).toString());
        TF_Bairro.setText(this.grid.getValueAt(index, 6).toString());
        TF_Cidade.setText(this.grid.getValueAt(index, 7).toString());
        TF_CEP.setText(this.grid.getValueAt(index, 8).toString());
        TF_UF.setText(this.grid.getValueAt(index, 9).toString());        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InclusaoDeFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InclusaoDeFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InclusaoDeFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InclusaoDeFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InclusaoDeFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Cancelar;
    private javax.swing.JButton B_Gravar;
    private javax.swing.JLabel L_Bairro;
    private javax.swing.JLabel L_CEP;
    private javax.swing.JLabel L_Cidade;
    private javax.swing.JLabel L_Codigo;
    private javax.swing.JLabel L_Endereco;
    private javax.swing.JLabel L_Nome;
    private javax.swing.JLabel L_Numero;
    private javax.swing.JLabel L_RG;
    private javax.swing.JLabel L_UF;
    private javax.swing.JRadioButton RB_CNPJ;
    private javax.swing.JRadioButton RB_CPF;
    private javax.swing.JTextField TF_Bairro;
    private javax.swing.JTextField TF_CEP;
    private javax.swing.JTextField TF_Cidade;
    private javax.swing.JTextField TF_Codigo;
    private javax.swing.JTextField TF_Documento;
    private javax.swing.JTextField TF_Endereco;
    private javax.swing.JTextField TF_Nome;
    private javax.swing.JTextField TF_Numero;
    private javax.swing.JTextField TF_RG;
    private javax.swing.JTextField TF_UF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
