/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ft.lojadamusica.janelas.compras.itens;

import br.unicamp.ft.lojadamusica.armazenamento.Arquivo;
import br.unicamp.ft.lojadamusica.janelas.produtos.EscolhaDeProduto;
import br.unicamp.ft.lojadamusica.janelas.produtos.ProcDadosPro;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zeh Fiorillo
 */
public class InclusaoDeItemNaCompra extends javax.swing.JFrame {        
    private String tipo;
    private JTable grid;
    private JTextField TF_ValTot;
    private int codcomp;
    private int qtdest;
    private int index;
    private int qtd_old;
    /**
     * Creates new form IncItemVenda
     */
    public InclusaoDeItemNaCompra() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_Produtom = new javax.swing.JLabel();
        TF_Produto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_ValUni = new javax.swing.JTextField();
        L_Quantidade = new javax.swing.JLabel();
        TF_Qtd = new javax.swing.JTextField();
        B_EscProd = new javax.swing.JButton();
        B_Gravar = new javax.swing.JButton();
        B_Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TF_Codigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loja da Musica - Incluir Item da Compra");

        L_Produtom.setText("Produto:");

        TF_Produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_ProdutoFocusLost(evt);
            }
        });

        jLabel2.setText("Valor Un.:");

        TF_ValUni.setEditable(false);

        L_Quantidade.setText("Quantidade:");

        B_EscProd.setText("...");
        B_EscProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_EscProdMouseClicked(evt);
            }
        });

        B_Gravar.setText("Gravar");
        B_Gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_GravarMouseClicked(evt);
            }
        });

        B_Cancelar.setText("Cancelar");
        B_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CancelarMouseClicked(evt);
            }
        });

        jLabel1.setText("Código:");

        TF_Codigo.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_Gravar)
                        .addGap(18, 18, 18)
                        .addComponent(B_Cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_Quantidade)
                            .addComponent(jLabel2)
                            .addComponent(L_Produtom)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TF_Produto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_EscProd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_ValUni, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(TF_Qtd, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(TF_Codigo))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Produtom)
                    .addComponent(TF_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_EscProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_ValUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Quantidade)
                    .addComponent(TF_Qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Gravar)
                    .addComponent(B_Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CancelarMouseClicked
        dispose();
    }//GEN-LAST:event_B_CancelarMouseClicked

    private void B_GravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_GravarMouseClicked
        if(TF_Produto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Produto é Obrigatório!");
            return;
        }        
        if(TF_Qtd.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Quantidade é Obrigatório!");
            return;
        }    
        if(!validaQtd()){
            JOptionPane.showMessageDialog(null, "Campo Qtde. Inválido!");
            TF_Qtd.grabFocus();
            return;
        }        
        double total = Double.valueOf(TF_ValTot.getText());
        double item = Double.valueOf(TF_ValUni.getText()) * Double.valueOf(TF_Qtd.getText());
        if(tipo=="A")
            total = total - (qtd_old * Double.valueOf(TF_ValUni.getText()));
        total = total + item;        
        TF_ValTot.setText(String.valueOf(total));
        DefaultTableModel modelo = (DefaultTableModel)grid.getModel();
        ItemCompra vItemCompra = new ItemCompra(Integer.valueOf(TF_Codigo.getText()),
                                                codcomp,
                                                Integer.valueOf(TF_Produto.getText()),
                                                Integer.valueOf(TF_Qtd.getText()),
                                                Double.valueOf(TF_ValUni.getText()));
        if(tipo=="A")
            modelo.removeRow(index);
        modelo.addRow(new Object [] {vItemCompra.getCodigo(),
                                     vItemCompra.getCodPro(),
                                     vItemCompra.getQtd(),
                                     vItemCompra.getValUni()});        
        dispose();
    }//GEN-LAST:event_B_GravarMouseClicked

    private void B_EscProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_EscProdMouseClicked
        EscolhaDeProduto varescprod = null;
        try {
            varescprod = new EscolhaDeProduto();
            qtdest = 0;
            varescprod.carregaInfo(TF_Produto, TF_ValUni);            
        } catch (IOException ex) {
            Logger.getLogger(InclusaoDeItemNaCompra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InclusaoDeItemNaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        TF_Qtd.grabFocus();
        varescprod.show();
    }//GEN-LAST:event_B_EscProdMouseClicked

    private void TF_ProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_ProdutoFocusLost
        if(!TF_Produto.getText().isEmpty()){
            ProcDadosPro vProcDados = new ProcDadosPro();
            try {                
                double valor = vProcDados.existeProduto(TF_Produto.getText());                
                if(valor==-1){
                    JOptionPane.showMessageDialog(null, "Produto Inválido!");
                    TF_Produto.grabFocus();
                    return;
                }
                else{
                    TF_ValUni.setText(String.valueOf(valor));
                    TF_Qtd.grabFocus();
                }                    
            } catch (IOException ex) {
                Logger.getLogger(InclusaoDeItemNaCompra.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(InclusaoDeItemNaCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_TF_ProdutoFocusLost

    private boolean validaQtd() { 
        try{
            int qtd = Integer.valueOf(TF_Qtd.getText());
        } catch (NumberFormatException ex){
            return false;
        }
        return true;
    }
    
    public void carregaInfo(String tipo, JTable grid, JTextField TF_ValTot, int codcomp, int index){
        this.tipo = tipo;        
        this.grid = grid;
        this.TF_ValTot = TF_ValTot;
        this.codcomp = codcomp;
        this.index = index;
        if(tipo == "I"){
            int codigo;
            if(this.grid.getRowCount()>0)
                codigo = Integer.valueOf(grid.getValueAt(this.grid.getRowCount()-1, 0).toString())+1;
            else
                codigo = 1;
            TF_Codigo.setText(String.valueOf(grid.getRowCount()+1));
        }
        else
            Alterar();
    }
    
    public void Alterar(){
        int index = this.grid.getSelectedRow();                
        TF_Codigo.setText(this.grid.getValueAt(index, 0).toString());
        TF_Produto.setText(this.grid.getValueAt(index, 1).toString());
        TF_Qtd.setText(this.grid.getValueAt(index, 2).toString());
        TF_ValUni.setText(this.grid.getValueAt(index, 3).toString());
        qtd_old = Integer.valueOf(this.grid.getValueAt(index, 2).toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InclusaoDeItemNaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InclusaoDeItemNaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InclusaoDeItemNaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InclusaoDeItemNaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InclusaoDeItemNaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Cancelar;
    private javax.swing.JButton B_EscProd;
    private javax.swing.JButton B_Gravar;
    private javax.swing.JLabel L_Produtom;
    private javax.swing.JLabel L_Quantidade;
    private javax.swing.JTextField TF_Codigo;
    private javax.swing.JTextField TF_Produto;
    private javax.swing.JTextField TF_Qtd;
    private javax.swing.JTextField TF_ValUni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
